# Generated by Django 4.1 on 2024-07-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_post_author_post_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_title', models.CharField(max_length=250)),
                ('head_descr', models.CharField(max_length=500)),
                ('head_img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
