# Generated by Django 4.1 on 2024-07-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comments_comments_blog_commen_created_ad0231_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='body',
            new_name='commentaire',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='name',
            new_name='nom',
        ),
    ]
