# Generated by Django 5.0.7 on 2024-07-22 17:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_image1_post_image2_post_image3_post_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
