# Generated by Django 5.0.7 on 2024-11-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_body2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image4',
        ),
    ]
